### ISSUE TITLE
Wasm decoding failed: mutable globals cannot be exported @+282

### ISSUE THREAD

**Issue by olelis** [ChainSafe/as-sha256#44]
Hello,

currently, there is a issue with this package.

When you run example from the readme, you will get following error:

```
\node_modules\@chainsafe\as-sha256\lib\wasm.js:17
const _module = new WebAssembly.Module(_buffer.Buffer.from(wasmCode, 'binary'));
                ^
CompileError: WebAssembly.Module(): Wasm decoding failed: mutable globals cannot be exported @+282

```
Environment:
node : v10.15.3

typescript 4.1.3

Any advices?

**Comment by MaxGraey** [comment]
too old node.js which not support mutable globals

**Comment by olelis** [comment]
Yep. Solution is to update to nodejs 14 or latest.
