### ISSUE TITLE
INPUT_LENGTH is undefined

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/as-sha256#47]
Manually modifying the built code and inspecting a run I noticed that `INPUT_LENGTH` was always undefined, so the code never goes into this path because `Number < undefined` is always `false`.

https://github.com/ChainSafe/as-sha256/blob/3fe48311c870298a273f9bb0c1e2e048263c3948/src/index.js#L34

To reproduce run the library with
```ts
const sha256 = require("bcrypto/lib/sha256");
as_sha256_1.default.digest(Buffer.concat([a, b]));
```
attach and debugger or console.log and inspect the value

**Comment by g11in** [comment]
@dapplion this is fixed, it can be closed.
